// <auto-generated />
using System;
using KeyPulse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyPulse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501051938_AddTotalInputCountToDevices")]
    partial class AddTotalInputCountToDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("KeyPulse.Models.ActivitySnapshot", b =>
                {
                    b.Property<int>("ActivitySnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Keystrokes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Minute")
                        .HasColumnType("TEXT");

                    b.Property<int>("MouseClicks")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MouseMovementSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivitySnapshotId");

                    b.HasIndex("Minute")
                        .HasDatabaseName("Idx_ActivitySnapshots_Minute");

                    b.HasIndex("DeviceId", "Minute")
                        .IsUnique()
                        .HasDatabaseName("Idx_ActivitySnapshots_DeviceIdMinute");

                    b.ToTable("ActivitySnapshots", (string)null);
                });

            modelBuilder.Entity("KeyPulse.Models.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ConnectionDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SessionStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalInputCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("Idx_Devices_DeviceId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("KeyPulse.Models.DeviceEvent", b =>
                {
                    b.Property<int>("DeviceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceEventId");

                    b.HasIndex("EventTime")
                        .HasDatabaseName("Idx_DeviceEvents_EventTime");

                    b.HasIndex("DeviceId", "EventTime")
                        .HasDatabaseName("Idx_DeviceEvents_DeviceIdEventTime");

                    b.HasIndex("DeviceId", "EventTime", "EventType")
                        .IsUnique()
                        .HasDatabaseName("Idx_DeviceEvents_Unique");

                    b.ToTable("DeviceEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
