// <auto-generated />
using System;
using KeyPulse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeyPulse.Migrations.PostgreSql
{
    [DbContext(typeof(PostgreSqlApplicationDbContext))]
    [Migration("20260715055119_PostgreSqlInitial")]
    partial class PostgreSqlInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeyPulse.Models.ActivityProjection", b =>
                {
                    b.Property<int>("ActivityProjectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityProjectionId"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Minute")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProjectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivityProjectionId");

                    b.HasIndex("DeviceId", "Minute")
                        .IsUnique()
                        .HasDatabaseName("Idx_ActivityProjections_DeviceIdMinute");

                    b.ToTable("ActivityProjections", (string)null);
                });

            modelBuilder.Entity("KeyPulse.Models.ActivitySnapshot", b =>
                {
                    b.Property<int>("ActivitySnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivitySnapshotId"));

                    b.Property<byte>("ActiveSeconds")
                        .HasColumnType("smallint");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Keystrokes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Minute")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MouseClicks")
                        .HasColumnType("integer");

                    b.Property<byte>("MouseMovementSeconds")
                        .HasColumnType("smallint");

                    b.HasKey("ActivitySnapshotId");

                    b.HasIndex("Minute")
                        .HasDatabaseName("Idx_ActivitySnapshots_Minute");

                    b.HasIndex("DeviceId", "Minute")
                        .IsUnique()
                        .HasDatabaseName("Idx_ActivitySnapshots_DeviceIdMinute");

                    b.ToTable("ActivitySnapshots", (string)null);
                });

            modelBuilder.Entity("KeyPulse.Models.DailyDeviceStat", b =>
                {
                    b.Property<int>("DailyDeviceStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyDeviceStatId"));

                    b.Property<long>("ActiveSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("ConnectionSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HourlyInputCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Keystrokes")
                        .HasColumnType("bigint");

                    b.Property<long>("MouseClicks")
                        .HasColumnType("bigint");

                    b.Property<long>("MouseMovementSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("SessionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DailyDeviceStatId");

                    b.HasIndex("Day")
                        .HasDatabaseName("Idx_DailyDeviceStats_Day");

                    b.HasIndex("Day", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("Idx_DailyDeviceStats_DayDeviceId");

                    b.HasIndex("DeviceId", "Day")
                        .HasDatabaseName("Idx_DailyDeviceStats_DeviceIdDay");

                    b.ToTable("DailyDeviceStats", (string)null);
                });

            modelBuilder.Entity("KeyPulse.Models.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<int>("DaysConnected")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHiddenFromDisplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SessionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalConnectionSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalInputCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("Idx_Devices_DeviceId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("KeyPulse.Models.DeviceEvent", b =>
                {
                    b.Property<int>("DeviceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceEventId"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceEventId");

                    b.HasIndex("EventTime")
                        .HasDatabaseName("Idx_DeviceEvents_EventTime");

                    b.HasIndex("DeviceId", "EventTime")
                        .HasDatabaseName("Idx_DeviceEvents_DeviceIdEventTime");

                    b.HasIndex("DeviceId", "EventTime", "EventType")
                        .IsUnique()
                        .HasDatabaseName("Idx_DeviceEvents_Unique");

                    b.ToTable("DeviceEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
